# docker-compose.yaml
services:
  tests:
    container_name: django
    env_file: ../private/secrets.txt
    build:
      context: .
      dockerfile: Dockerfile.client
  backend:
    env_file: ../private/secrets.txt
    image: postgres:15-bullseye
    restart: always
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports: 
      - 5432:5432
